module.exports = [
  {
    seed_key:'treasure-brush', section_key:'treasures', symbol_zh:'笔', symbol_en:'Brush', label_zh:'brush', label_en:'brush',
    title_zh:'毛笔', title_en:'Brushes', summary_zh:'狼毫 · 羊毫 · 兼毫', summary_en:'Weasel Hair · Goat Hair · Mixed Hair', sort_order:1,
  },
  {
    seed_key:'treasure-ink', section_key:'treasures', symbol_zh:'墨', symbol_en:'Ink', label_zh:'ink', label_en:'ink',
    title_zh:'墨品', title_en:'Ink', summary_zh:'松烟 · 油烟 · 墨汁', summary_en:'Pine Soot · Oil Soot · Liquid Ink', sort_order:2,
  },
  {
    seed_key:'treasure-paper', section_key:'treasures', symbol_zh:'纸', symbol_en:'Paper', label_zh:'paper', label_en:'paper',
    title_zh:'宣纸', title_en:'Xuan Paper', summary_zh:'生宣 · 熟宣 · 半生熟', summary_en:'Raw · Sized · Semi-sized', sort_order:3,
  },
  {
    seed_key:'treasure-inkstone', section_key:'treasures', symbol_zh:'砚', symbol_en:'Inkstone', label_zh:'inkstone', label_en:'inkstone',
    title_zh:'砚台', title_en:'Inkstones', summary_zh:'端砚 · 歙砚 · 澄泥砚', summary_en:'Duan · She · Chengni', sort_order:4,
  },
  {
    seed_key:'artisan-brush', section_key:'artisans', symbol_zh:'笔', symbol_en:'Brush',
    label_zh:'制笔匠人', label_en:'Brush Maker', title_zh:'徐文清', title_en:'Xu Wenqing',
    meta_zh:'从业 42 年', meta_en:'42 Years in the Craft',
    summary_zh:'一支好笔，要经一百二十七道工序。每道工序都慢不得、省不得。做笔一辈子，我最看重的是「四德」——尖、齐、圆、健。',
    summary_en:'A fine brush passes through 127 steps. None can be hurried or skipped. After a lifetime of making brushes, I still judge one by four virtues: a sharp point, even hairs, a full body, and resilient spring.',
    body_zh:'徐文清老先生是紫云湖制笔工坊的首席制笔师，出生于安徽宣城制笔世家，自16岁起便跟随父亲学习制笔技艺，至今已42载。\n\n他常说：「制笔如做人，要刚正不阿。笔杆要直，笔锋要正，笔心要齐。」从选料开始，徐师傅便亲力亲为。\n\n一支高档狼毫笔，从择毫到成品，要经过127道工序，其中大部分是纯手工完成。徐师傅最擅长的是「扎笔头」这道关键工序。\n\n如今，徐师傅已经开始带徒弟了。他最大的心愿就是让这门手艺一代一代传下去。',
    body_en:'Xu Wenqing is the senior brush maker at Ziyun Lake. Born into a brush-making family in Xuancheng, Anhui, he began learning from his father at sixteen.\n\nHe believes brush making mirrors character: the shaft, tip, and heart must all be true. He personally oversees every stage, beginning with the selection of hair.\n\nA premium brush passes through 127 steps, most completed entirely by hand. Today he teaches apprentices so the craft can continue for another generation.',
    sort_order:1,
  },
  {
    seed_key:'artisan-ink', section_key:'artisans', symbol_zh:'墨', symbol_en:'Ink',
    label_zh:'制墨匠人', label_en:'Ink Maker', title_zh:'程守墨', title_en:'Cheng Shoumo',
    meta_zh:'从业 36 年', meta_en:'36 Years in the Craft',
    summary_zh:'墨者，黑也；然黑中有万千层次。好墨如好茶，要时间来陈。一方好墨，可传三代人。墨香越陈越醇，墨色越老越润。',
    summary_en:'Ink may be black, but black contains countless tones. Like fine tea, good ink matures with time; one stick can serve three generations, growing mellower and richer as it ages.',
    body_zh:'程守墨师傅是安徽歙县人，祖上三代制墨，到他这辈已是第四代。程师傅的墨庄名为「守墨堂」，取「守墨如守心」之意。\n\n制墨最核心的工序是「点烟」。古法点烟，是将桐油或松脂点燃，用瓷碗罩在火焰上方收集烟灰。\n\n程师傅的墨，每年只做几百斤，供不应求。但他从不增产：「制墨是手工活，多了就做不精。宁少勿滥。」',
    body_en:'Cheng Shoumo comes from She County, Anhui, and represents the fourth generation of his family to make ink. His workshop name means guarding ink as carefully as one guards the heart.\n\nThe essential step is collecting soot from burning tung oil or pine resin. Fine ink is then mixed, repeatedly pounded, shaped, and patiently aged.\n\nHe deliberately keeps production small: handmade ink loses its character when quantity overtakes care.',
    sort_order:2,
  },
  {
    seed_key:'artisan-paper', section_key:'artisans', symbol_zh:'纸', symbol_en:'Paper',
    label_zh:'造纸匠人', label_en:'Papermaker', title_zh:'曹纸仙', title_en:'Cao Zhixian',
    meta_zh:'从业 38 年', meta_en:'38 Years in the Craft',
    summary_zh:'宣纸是有灵性的。同样的皮料、同样的工艺，不同的人抄出来的纸就是不一样。纸知道你有没有用心——墨一落纸，便见分晓。',
    summary_en:'Xuan paper has a spirit of its own. Give two people the same fiber and process and their sheets will still differ. The paper knows whether you worked with care—the instant ink touches it, the truth appears.',
    body_zh:'曹纸仙师傅是安徽泾县人，是曹氏宣纸第18代传人，从18岁开始学习造纸，至今已有38个春秋。\n\n一张宣纸，要经过108道工序，历时一年方能完成。其中最关键的是「抄纸」，纸张厚薄全凭匠人手感。\n\n曹师傅的儿子也在学造纸。他不催促，只愿把每一道工序认真教下去。',
    body_en:'Cao Zhixian is an eighteenth-generation Xuan papermaker from Jing County, Anhui. He began learning at eighteen and has practiced for thirty-eight years.\n\nA sheet of Xuan paper passes through 108 steps over the course of a year. The decisive moment is lifting the sheet, when thickness and balance depend entirely on the maker’s hands.\n\nHis son is now learning the craft, one patient process at a time.',
    sort_order:3,
  },
  {
    seed_key:'artisan-inkstone', section_key:'artisans', symbol_zh:'砚', symbol_en:'Inkstone',
    label_zh:'琢砚匠人', label_en:'Inkstone Carver', title_zh:'方砚秋', title_en:'Fang Yanqiu',
    meta_zh:'从业 35 年', meta_en:'35 Years in the Craft',
    summary_zh:'一方好砚，讲究「石品第一，刀法第二，造型第三」。砚是用来磨墨的，不是摆着看的。发墨快、不伤笔、不吸水，才是一方好砚的根本。',
    summary_en:'For a fine inkstone, stone quality comes first, carving second, and shape third. An inkstone should release ink quickly, protect the brush, and resist absorbing water.',
    body_zh:'方砚秋师傅是江西婺源人，是婺源歙砚雕刻的代表性传承人。方师傅16岁拜师学艺，从选石、开料、设计到雕刻，样样精通。\n\n他最擅长「因材施艺」，根据石头天然的纹理和形态设计雕刻图案。\n\n方师傅常说，砚台首先是文房工具，其次才是艺术品。实用与观赏，缺一不可。',
    body_en:'Fang Yanqiu is an inkstone carver from Wuyuan, Jiangxi. He entered an apprenticeship at sixteen and learned every stage from choosing and opening stone to design and carving.\n\nHis specialty is allowing the natural grain and form of each stone to guide the design.\n\nAn inkstone, he says, is first a working scholar’s tool and only then a work of art. Beauty and performance must remain inseparable.',
    sort_order:4,
  },
  {
    seed_key:'culture-brush', section_key:'culture', label_zh:'毛笔文化', label_en:'Brush Culture',
    title_zh:'如何选择一支适合自己的毛笔', title_en:'How to Choose the Right Chinese Brush',
    meta_zh:'8分钟 · 5,823人阅读', meta_en:'8 min · 5,823 reads',
    summary_zh:'面对琳琅满目的毛笔，初学者往往不知如何选择。本文从毫毛材质、字体适配、使用场景等角度，助你找到第一支称心之笔。',
    summary_en:'Choosing a first brush can feel daunting. This guide explains hair types, script sizes, and everyday uses so you can find a dependable first brush.',
    body_zh:'先看笔毫材质\n羊毫柔软、蓄墨量大；狼毫弹性较强、出锋利落；兼毫兼顾弹性与蓄墨，对初学者最友好。\n\n再按字体大小选笔锋\n小楷宜选锋短、腰力足的小笔；日常练习可选中楷或大楷；榜书、对联才需要斗笔。\n\n试笔时关注细节\n观察笔尖能否聚拢，轻压后能否回锋，并确认笔杆握持顺手。',
    body_en:'Start with the hair\nGoat hair is soft and ink-rich, weasel hair is springy and crisp, while mixed hair offers a forgiving balance for beginners.\n\nMatch the tip to your script\nUse a short, firm tip for small script, a medium or large brush for daily regular-script practice, and reserve very large brushes for monumental writing.\n\nCheck the details\nMake sure the tip gathers evenly, recovers after gentle pressure, and feels comfortable in the hand.',
    sort_order:1,
  },
  {
    seed_key:'culture-paper', section_key:'culture', label_zh:'宣纸知识', label_en:'Xuan Paper Guide',
    title_zh:'生宣、熟宣、半生熟的区别与选用', title_en:'Raw, Sized, and Semi-sized Xuan Paper',
    meta_zh:'6分钟 · 4,156人阅读', meta_en:'6 min · 4,156 reads',
    summary_zh:'宣纸分生宣、熟宣、半生熟三大类，各有不同特性和适用场景。了解纸性，才能让书画创作事半功倍。',
    summary_en:'Xuan paper comes in raw, sized, and semi-sized forms. Understanding how each behaves makes calligraphy and painting easier to control.',
    body_zh:'生宣：吸水快，墨色变化丰富\n适合写意花鸟、山水以及行草书。\n\n熟宣：不易渗化，适合精细刻画\n适合工笔画、小楷和界画，应避免反复折叠或重压。\n\n半生熟：兼顾控制与墨韵\n既保留一定渗化效果，又比生宣容易控制，适合初学书法和写意小品。',
    body_en:'Raw Xuan\nFast absorption creates rich ink variation for expressive painting and running or cursive script.\n\nSized Xuan\nA controlled surface supports fine lines, layered color, gongbi painting, and small script.\n\nSemi-sized Xuan\nA middle ground that preserves some diffusion while remaining easier to control.',
    sort_order:2,
  },
  {
    seed_key:'culture-inkstone', section_key:'culture', label_zh:'砚台保养', label_en:'Inkstone Care',
    title_zh:'砚台保养指南：如何让一方宝砚传家百年', title_en:'Inkstone Care: Preserving a Treasure for Generations',
    meta_zh:'10分钟 · 2,987人阅读', meta_en:'10 min · 2,987 reads',
    summary_zh:'一方好砚可传家，但保养不当也会损伤石质与发墨性能。本文详解清洗、存放与研墨的要点。',
    summary_en:'A fine inkstone can serve generations when cared for well. Learn how to clean, store, and use one without damaging its stone or ink-making qualities.',
    body_zh:'用后及时清洗\n使用后以清水和柔软海绵轻洗，不要使用洗涤剂、硬毛刷或金属工具。\n\n保持适度湿润，但不要久泡\n置于阴凉、通风、温湿度稳定的环境，避免突然暴晒或靠近暖气。\n\n正确研墨与存放\n保持墨锭垂直，力度均匀；长期不用时彻底清洁并自然阴干。',
    body_en:'Clean soon after use\nRinse with clean water and a soft sponge. Avoid detergents, stiff brushes, and metal tools.\n\nAvoid extremes\nKeep the stone in a cool, ventilated place and never leave it soaking or expose it to sudden heat.\n\nGrind and store with care\nHold the ink stick upright with even pressure. Clean and air-dry the stone before long-term storage.',
    sort_order:3,
  },
  {
    seed_key:'story-origin', section_key:'brand_story', symbol_zh:'壹', symbol_en:'I', title_zh:'溯源', title_en:'Origins',
    summary_zh:'紫云湖品牌源自徽州湖畔百年制笔世家，世代传承文房制作技艺，最早可追溯至清光绪年间的「紫云轩」笔庄。',
    summary_en:'Ziyun Lake traces its roots to a Huizhou brush-making family whose workshop, Ziyun Studio, dates to the late Qing dynasty.', sort_order:1,
  },
  {
    seed_key:'story-craft', section_key:'brand_story', symbol_zh:'贰', symbol_en:'II', title_zh:'匠心', title_en:'Craft',
    summary_zh:'每一件文房器物皆经百余道工序，由非遗匠人纯手工打造。从选料至成品，历时数月乃至数载方得大成。',
    summary_en:'Each scholar’s object passes through scores of hand processes, from careful material selection to months—or years—of patient finishing.', sort_order:2,
  },
  {
    seed_key:'story-legacy', section_key:'brand_story', symbol_zh:'叁', symbol_en:'III', title_zh:'传承', title_en:'Legacy',
    summary_zh:'我们坚信文房四宝不仅是工具，更是中华文脉的载体。紫云湖致力于让传统文化在当代焕发新的生命力。',
    summary_en:'The Four Treasures are more than tools: they carry a literary tradition. Ziyun Lake helps that tradition remain useful, beautiful, and alive today.', sort_order:3,
  },
];
