const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
process.env.DB_PATH = ':memory:';
process.env.JWT_SECRET = crypto.randomBytes(32).toString('hex');
process.env.PAYMENT_CONFIG_KEY = crypto.randomBytes(32).toString('base64');
require('../config/initDB');
const db = require('../config/db');
const { providers } = require('../services/payments');
const originalProviders = { alipay: { ...providers.alipay }, wechat: { ...providers.wechat } };
const jwt = require('jsonwebtoken');
const express = require('express');
const keypair = crypto.generateKeyPairSync('rsa', { modulusLength: 2048, publicKeyEncoding: {type:'spki',format:'pem'}, privateKeyEncoding:{type:'pkcs8',format:'pem'} });

test('commerce API: stock, checkout, payment trust and merchant settings', async t => {
  const app = express();
  app.use(express.json({verify:(req,res,body)=>{req.rawBody=body;}}));
  app.use(express.urlencoded({extended:false}));
  for (const [url,file] of [['cart','cart'],['orders','orders'],['payment','payment'],['admin','admin'],['admin/payment-settings','payment-settings'],['admin/personal-payments','personal-payments'],['products','products']]) app.use('/api/'+url,require('../routes/'+file));
  app.use((err,req,res,next)=>res.status(err.status||500).json({code:err.status||500,message:err.message}));
  const server = app.listen(0,'127.0.0.1');
  await new Promise(resolve=>server.once('listening',resolve));
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();});
  const base='http://127.0.0.1:'+server.address().port+'/api';
  db.prepare("INSERT INTO users(username,password) VALUES('buyer','unused'),('other','unused')").run();
  const buyer=db.prepare("SELECT id FROM users WHERE username='buyer'").get().id;
  const other=db.prepare("SELECT id FROM users WHERE username='other'").get().id;
  const admin=db.prepare("SELECT id FROM users WHERE username='admin'").get().id;
  async function request(url,method='GET',body,uid=buyer) {
    const version=uid ? db.prepare('SELECT session_version FROM users WHERE id=?').get(uid).session_version : 0;
    const response=await fetch(base+url,{method,headers:{'Content-Type':'application/json',...(uid?{Authorization:'Bearer '+jwt.sign({id:uid,session_version:version},process.env.JWT_SECRET)}:{})},body:body===undefined?undefined:JSON.stringify(body)});
    const raw=await response.text(); let data; try{data=JSON.parse(raw);}catch{data=raw;}
    return {status:response.status,body:data,cacheControl:response.headers.get('cache-control')};
  }
  const product = () => Number(db.prepare("INSERT INTO products(name,category,price,stock,spec,image) VALUES('测试毛笔','pen',68.50,5,'中楷','/uploads/brush.png')").run().lastInsertRowid);
  const body = items => ({receiver_name:'买家',receiver_phone:'13800138000',receiver_address:'测试省测试市测试路1号',items});
  const stock=id=>db.prepare('SELECT stock FROM products WHERE id=?').get(id).stock;
  const getOrder=id=>db.prepare('SELECT * FROM orders WHERE id=?').get(id);
  const make=async(id,qty=1)=> (await request('/orders','POST',body([{product_id:id,quantity:qty}]))).body.data;

  await t.test('cart rejects non-integer/negative quantities and caps against stock',async()=>{
    const id=product();
    for(const qty of [-1,0,1.5,'2',null,1000001]) assert.equal((await request('/cart','POST',{product_id:id,quantity:qty})).status,400);
    assert.equal((await request('/cart','POST',{product_id:id,quantity:2})).status,200);
    const item=(await request('/cart')).body.data.list.find(x=>x.product_id===id);
    assert.equal(item.quantity,2); assert.equal(item.stock,5);
    assert.equal((await request('/cart/'+item.id,'PUT',{quantity:6})).status,400);
    assert.equal((await request('/cart/'+item.id,'PUT',{quantity:1.2})).status,400);
    assert.equal((await request('/cart/'+item.id,'PUT',{quantity:3})).status,200);
    assert.equal((await request('/cart/'+item.id,'PUT',{quantity:1},other)).status,404);
    db.prepare('UPDATE products SET status=0 WHERE id=?').run(id);
    assert.equal((await request('/cart','POST',{product_id:id,quantity:1})).status,404);
    await request('/cart','DELETE');
  });
  await t.test('server prices and snapshots defeat forged item fields; duplicate lines aggregate',async()=>{
    const id=product();
    const result=await request('/orders','POST',body([{product_id:id,quantity:1,price:0.01,name:'假商品'},{product_id:id,quantity:1,price:-10}]));
    assert.equal(result.status,200); const order=result.body.data;
    assert.equal(order.total_amount,149); assert.equal(order.freight,12); assert.equal(order.items.length,1);
    assert.equal(order.items[0].quantity,2);assert.equal(order.items[0].price,68.5);assert.equal(order.items[0].product_name,'测试毛笔');
    assert.equal(order.items[0].image,'/uploads/brush.png');assert.ok(order.created_at);assert.equal(stock(id),3);
    assert.equal((await request('/orders/'+order.id,'GET',undefined,other)).status,404);
    const before=db.prepare('SELECT COUNT(*) n FROM orders').get().n;
    assert.equal((await request('/orders','POST',body([{product_id:id,quantity:2},{product_id:id,quantity:2}]))).status,409);
    assert.equal(stock(id),3);assert.equal(db.prepare('SELECT COUNT(*) n FROM orders').get().n,before);
  });
  await t.test('invalid order inputs cannot create inventory or malformed orders',async()=>{
    const id=product();
    for(const items of [[],{},[{product_id:id,quantity:-2}],[{product_id:id,quantity:'1'}],[{product_id:id,quantity:1.1}], [null]]) assert.equal((await request('/orders','POST',body(items))).status,400);
    assert.equal(stock(id),5);
  });
  await t.test('last stock is sold once; idempotency avoids repeated checkout and preserves unrelated cart',async()=>{
    const id=product();
    db.prepare('UPDATE products SET stock=1 WHERE id=?').run(id);
    const results=await Promise.all([make(id),make(id)]);
    assert.equal(results.filter(Boolean).length,1); assert.equal(stock(id),0);
    const id2=product();
    await request('/cart','POST',{product_id:id2,quantity:2});
    const input={...body(undefined),checkout_key:crypto.randomUUID()};
    const first=await request('/orders','POST',input), second=await request('/orders','POST',input);
    assert.equal(first.status,200); assert.equal(first.body.data.id,second.body.data.id);assert.equal(stock(id2),3);
    assert.equal((await request('/cart')).body.data.list.length,0);
    await request('/cart','POST',{product_id:id2,quantity:1});
    await make(id2);
    assert.equal((await request('/cart')).body.data.list.length,1);
    await request('/cart','DELETE');
  });
  await t.test('cancel restores inventory exactly once and cannot be reopened or marked paid by admin',async()=>{
    const id=product(), order=await make(id,2);
    assert.equal((await request('/orders/'+order.id+'/cancel','PUT',{})).status,200);
    assert.equal(stock(id),5);
    assert.equal((await request('/orders/'+order.id+'/cancel','PUT',{})).status,409);assert.equal(stock(id),5);
    assert.equal((await request('/admin/orders/'+order.id+'/status','PUT',{status:'paid'},admin)).status,400);
    assert.equal((await request('/admin/orders/'+order.id+'/status','PUT',{status:'pending'},admin)).status,400);
  });
  await t.test('admin stock edits are authorized and reject stale writes, negatives and fractions',async()=>{
    const id=product();
    assert.equal((await request('/admin/products/'+id+'/stock','PUT',{stock:8,expected_stock:5})).status,403);
    assert.equal((await request('/admin/products/'+id+'/stock','PUT',{stock:-1,expected_stock:5},admin)).status,400);
    assert.equal((await request('/admin/products/'+id+'/stock','PUT',{stock:1.2,expected_stock:5},admin)).status,400);
    assert.equal((await request('/admin/products/'+id+'/stock','PUT',{stock:8,expected_stock:5},admin)).status,200);
    assert.equal((await request('/admin/products/'+id+'/stock','PUT',{stock:9,expected_stock:5},admin)).status,409);
    assert.equal((await request('/admin/products/'+id,'PUT',{stock:9,expected_stock:5},admin)).status,409);assert.equal(stock(id),8);
    assert.equal((await request('/admin/products/'+id,'PUT',{stock:0,expected_stock:8},admin)).status,200);assert.equal(stock(id),0);
    assert.equal((await request('/products/'+id)).body.data.stock,0);
  });
  await t.test('unconfigured payment and legacy card methods never mark an order paid',async()=>{
    const order=await make(product());
    assert.equal((await request('/payment/pay','POST',{order_id:order.id,payment_method:'alipay'})).status,503);
    assert.equal((await request('/payment/pay','POST',{order_id:order.id,payment_method:'bankcard'})).status,400);
    assert.equal((await request('/payment/alipay/notify','POST',{out_trade_no:order.order_no,trade_status:'TRADE_SUCCESS'},null)).status,400);
    assert.equal(getOrder(order.id).status,'pending');
  });
  await t.test('provider initiation waits for verified money and signed callbacks are idempotent',async()=>{
    const id=product(), order=await make(id,2);
    const {createAlipay}=require('../services/alipay-live');
    const real=createAlipay({appId:'2026000123456789',sellerId:'2088000123456789',privateKey:keypair.privateKey,alipayPublicKey:keypair.publicKey,keyType:'PKCS8',notifyUrl:'https://shop.test/api/payment/alipay/notify',returnUrl:'https://shop.test/'});
    Object.assign(providers.alipay,real);
    const started=await request('/payment/pay','POST',{order_id:order.id,payment_method:'alipay'});
    assert.equal(started.status,200);assert.ok(started.body.data.payUrl.startsWith('https://openapi.alipay.com/'));
    assert.equal(getOrder(order.id).status,'pending');assert.equal(stock(id),3);
    const params={app_id:'2026000123456789',seller_id:'2088000123456789',out_trade_no:order.order_no,total_amount:'149.00',trade_no:'test-trade-1',trade_status:'TRADE_SUCCESS',sign_type:'RSA2'};
    function signed(extra={}) {const p={...params,...extra};const value=Object.keys(p).filter(k=>k!=='sign_type').sort().map(k=>k+'='+p[k]).join('&');return {...p,sign:crypto.sign('RSA-SHA256',Buffer.from(value),keypair.privateKey).toString('base64')};}
    for(const extra of [{total_amount:'0.01'},{app_id:'wrong'},{seller_id:'wrong'}]) assert.equal((await request('/payment/alipay/notify','POST',signed(extra),null)).status,400);
    assert.equal(getOrder(order.id).status,'pending');
    assert.equal((await request('/payment/alipay/notify','POST',signed(),null)).status,200);
    assert.equal((await request('/payment/alipay/notify','POST',signed(),null)).status,200);
    assert.equal(getOrder(order.id).payment_transaction_id,'test-trade-1');assert.equal(stock(id),3);
    assert.equal((await request('/orders/'+order.id+'/cancel','PUT',{})).status,409);
    assert.equal((await request('/payment/pay','POST',{order_id:order.id,payment_method:'alipay'})).status,409);
    Object.assign(providers.alipay,originalProviders.alipay);
  });
  await t.test('close failures keep reservations; server query detects payment before cancellation',async()=>{
    const id=product(),order=await make(id);
    db.prepare("UPDATE orders SET payment_method='wechat' WHERE id=?").run(order.id);
    Object.assign(providers.wechat,{isReady:true,query:async()=>({state:'NOTPAY'}),close:async()=>{throw Object.assign(Error('provider unavailable'),{status:502});}});
    assert.equal((await request('/orders/'+order.id+'/cancel','PUT',{})).status,502);assert.equal(stock(id),4);assert.equal(getOrder(order.id).status,'pending');
    providers.wechat.query=async()=>({state:'SUCCESS',payment:{orderNo:order.order_no,amountCents:8050,transactionId:'wechat-query-1'}});
    assert.equal((await request('/orders/'+order.id+'/cancel','PUT',{})).status,409);assert.equal(getOrder(order.id).status,'paid');assert.equal(stock(id),4);
    Object.assign(providers.wechat,originalProviders.wechat);
  });
  await t.test('merchant settings enforce admin/password, encrypt secrets and never echo them',async()=>{
    assert.equal((await request('/admin/payment-settings')).status,403);
    const input={enabled:true,appId:'2026000123456789',sellerId:'2088000123456789',keyType:'PKCS8',privateKey:keypair.privateKey,alipayPublicKey:keypair.publicKey,notifyUrl:'https://shop.test/api/payment/alipay/notify',returnUrl:'https://shop.test/'};
    assert.equal((await request('/admin/payment-settings/alipay','PUT',{settings:input,admin_password:'admin123'},admin)).status,403);
    assert.equal((await request('/admin/payment-settings/password','PUT',{admin_password:'admin123',new_password:'Merchant123456!'},admin)).status,200);
    const save=await request('/admin/payment-settings/alipay','PUT',{settings:input,admin_password:'Merchant123456!'},admin);
    assert.equal(save.status,200,JSON.stringify(save.body));
    const saved=(await request('/admin/payment-settings','GET',undefined,admin)).body.data;
    assert.equal(saved.alipay.configured,true);assert.equal(saved.alipay.secretSet.privateKey,true);assert.equal(saved.alipay.fields.privateKey,undefined);
    assert.ok(!JSON.stringify(saved).includes(keypair.privateKey));
    const encrypted=db.prepare('SELECT payload FROM payment_settings').get().payload;
    assert.ok(!encrypted.includes('PRIVATE KEY'));assert.ok(!encrypted.includes(input.appId));
    assert.equal(require('../services/payment-settings').readSettings().alipay.privateKey,keypair.privateKey.trim());
    assert.equal((await request('/admin/payment-settings/alipay','PUT',{settings:{...input,privateKey:'invalid'},admin_password:'Merchant123456!'},admin)).status,400);
  });
  const personalUrl='/uploads/personal-'+crypto.randomUUID()+'.png';
  const personalFile=path.join(__dirname,'..','public',personalUrl);
  fs.mkdirSync(path.dirname(personalFile),{recursive:true});
  fs.writeFileSync(personalFile,await require('qrcode').toBuffer('test-only-not-a-payment-code'));
  t.after(()=>fs.unlinkSync(personalFile));
  const personalSettings={enabled:true,qr_url:personalUrl,recipient:'测试收款人',instructions:'仅用于自动化测试，不可付款',admin_password:'Merchant123456!'};
  const review=(order,extra={},uid=admin)=>request('/admin/personal-payments/orders/'+order.id+'/review','POST',{decision:'confirm',verified:true,amount:order.total_amount,reference:'test-reference-'+order.id,admin_password:'Merchant123456!',...extra},uid);
  await t.test('four payment methods are distinct; personal configuration is admin-only and does not change provider settings',async()=>{
    const methods=(await request('/payment/methods')).body.data;
    assert.deepEqual(methods.map(x=>x.name),['普通支付宝','普通微信','商户支付宝','商户微信']);
    assert.deepEqual(methods.map(x=>x.mode),['manual','manual','provider','provider']);
    assert.equal((await request('/admin/personal-payments','GET',undefined,null)).status,401);
    assert.equal((await request('/admin/personal-payments')).status,403);
    const order=await make(product());
    assert.equal((await request('/payment/pay','POST',{order_id:order.id,payment_method:'alipay_personal'})).status,503);
    assert.equal(getOrder(order.id).payment_method,null);
    assert.equal((await request('/admin/personal-payments/alipay_personal','PUT',{...personalSettings,admin_password:'wrong'},admin)).status,403);
    for(const qr_url of ['https://attacker.example/qr.png','/uploads/../secret.png','/uploads/ordinary.svg'])assert.equal((await request('/admin/personal-payments/alipay_personal','PUT',{...personalSettings,qr_url},admin)).status,400);
    assert.equal((await request('/admin/personal-payments/alipay_personal','PUT',{...personalSettings,recipient:''},admin)).status,200);
    for(const channel of ['alipay_personal','wechat_personal'])assert.equal((await request('/admin/personal-payments/'+channel,'PUT',personalSettings,admin)).status,200);
    assert.equal((await request('/payment/methods')).body.data.filter(x=>x.mode==='manual'&&x.enabled).length,2);
    assert.equal((await request('/admin/payment-settings','GET',undefined,admin)).body.data.alipay.fields.appId,'2026000123456789');
  });
  await t.test('personal QR upload checks administrator password and rejects disguised HTML',async()=>{
    const form=new FormData();form.append('file',new Blob(['<html>not a PNG</html>'],{type:'image/png'}),'qr.png');form.append('admin_password','Merchant123456!');
    const result=await fetch(base+'/admin/personal-payments/qr',{method:'POST',headers:{Authorization:'Bearer '+jwt.sign({id:admin,session_version:db.prepare('SELECT session_version FROM users WHERE id=?').get(admin).session_version},process.env.JWT_SECRET)},body:form});
    assert.equal(result.status,400);
    const good=new FormData();good.append('file',new Blob([fs.readFileSync(personalFile)],{type:'image/png'}),'qr.png');good.append('admin_password','Merchant123456!');
    const uploaded=await fetch(base+'/admin/personal-payments/qr',{method:'POST',headers:{Authorization:'Bearer '+jwt.sign({id:admin,session_version:db.prepare('SELECT session_version FROM users WHERE id=?').get(admin).session_version},process.env.JWT_SECRET)},body:good});
    assert.equal(uploaded.status,200);const image=(await uploaded.json()).data.url;
    assert.match(image,/^\/uploads\/personal-[a-z0-9-]+\.png$/);
    const uploadedFile=path.join(__dirname,'..','public',image);t.after(()=>fs.unlinkSync(uploadedFile));
    assert.deepEqual(fs.readFileSync(uploadedFile),fs.readFileSync(personalFile));
  });
  for(const channel of ['alipay_personal','wechat_personal']) await t.test(channel+': buyer reports transfer but only audited administrator verification permits shipping',async()=>{
    const id=product(),order=await make(id,2);
    const baseline=(await request('/admin/dashboard','GET',undefined,admin)).body.data.totalRevenue;
    const started=await request('/payment/pay','POST',{order_id:order.id,payment_method:channel});
    assert.equal(started.status,200);assert.equal(started.body.data.qrUrl,personalUrl);assert.equal(started.body.data.mode,'manual');assert.equal(started.body.data.amount,149);
    assert.equal(getOrder(order.id).status,'pending');assert.equal(stock(id),3);
    const merchant=channel==='alipay_personal'?'wechat_personal':'alipay_personal';
    assert.equal((await request('/payment/pay','POST',{order_id:order.id,payment_method:merchant})).status,409);
    assert.equal((await request('/orders/'+order.id+'/cancel','PUT',{})).status,409);
    assert.equal((await request('/payment/personal/'+order.id+'/claim','POST',{reference:'buyer-entered-reference'},other)).status,404);
    assert.equal((await request('/payment/personal/'+order.id+'/claim','POST',{reference:''})).status,400);
    const claim=await request('/payment/personal/'+order.id+'/claim','POST',{reference:'buyer-entered-reference',note:'test note',status:'paid',manual_confirmed_at:'forged'});
    assert.equal(claim.status,200);assert.equal(claim.body.data.status,'payment_review');assert.equal(claim.body.data.manual_confirmed_at,null);
    assert.equal((await request('/payment/personal/'+order.id+'/claim','POST',{reference:'retry'})).body.data.manual_claim_reference,'buyer-entered-reference');
    assert.equal((await request('/payment/status/'+order.order_no)).body.data.status,'payment_review');
    assert.equal((await request('/admin/orders/'+order.id+'/ship','PUT',{tracking_company:'test',tracking_no:'test'},admin)).status,400);
    assert.equal((await review(order,{},buyer)).status,403);
    for(const extra of [{amount:'0.01'},{verified:false},{reference:''}])assert.equal((await review(order,extra)).status,400);
    assert.equal((await review(order,{admin_password:'wrong'})).status,403);
    assert.equal((await request('/admin/orders/'+order.id+'/status','PUT',{status:'paid'},admin)).status,400);
    assert.equal((await review(order)).status,200);assert.equal((await review(order)).status,200);
    const paid=getOrder(order.id);assert.equal(paid.status,'paid');assert.equal(paid.payment_transaction_id,null);assert.ok(paid.manual_confirmed_at);assert.equal(paid.manual_confirmed_by,admin);
    const checked=await request('/payment/status/'+order.order_no);
    assert.equal(checked.body.data.status,'paid');assert.equal(checked.cacheControl,'no-store');
    assert.equal((await request('/orders/'+order.id)).cacheControl,'no-store');
    assert.equal((await request('/orders/'+order.id+'/confirm','PUT',{})).status,400);
    assert.equal(db.prepare('SELECT COUNT(*) n FROM manual_payment_audit WHERE order_id=?').get(order.id).n,1);assert.equal(stock(id),3);
    const buyerView=(await request('/orders/'+order.id)).body.data;assert.ok(buyerView.manual_confirmed_at);assert.equal(buyerView.manual_transaction_reference,undefined);assert.equal(buyerView.manual_confirmed_by,undefined);
    assert.equal((await request('/admin/dashboard','GET',undefined,admin)).body.data.totalRevenue,baseline+149);
    const duplicate=await make(product());await request('/payment/pay','POST',{order_id:duplicate.id,payment_method:channel});
    assert.equal((await review(duplicate,{reference:'test-reference-'+order.id})).status,409);
    assert.equal((await request('/admin/orders/'+order.id+'/ship','PUT',{tracking_company:'test',tracking_no:'test'},admin)).status,200);
    const pointsBefore=db.prepare('SELECT points FROM users WHERE id=?').get(buyer).points;
    assert.equal((await request('/orders/'+order.id+'/confirm','PUT',{})).status,200);
    assert.equal(getOrder(order.id).status,'completed');assert.equal(stock(id),3);
    assert.equal((await request('/orders/'+order.id+'/confirm','PUT',{})).status,400);
    assert.equal(db.prepare('SELECT points FROM users WHERE id=?').get(buyer).points,pointsBefore+Math.floor(order.total_amount));
  });
  await t.test('manual rejection, immutable QR snapshot and verified cancellation preserve inventory',async()=>{
    const id=product(),order=await make(id);await request('/payment/pay','POST',{order_id:order.id,payment_method:'alipay_personal'});
    await request('/payment/personal/'+order.id+'/claim','POST',{reference:'test'});
    assert.equal((await review(order,{decision:'reject',note:''})).status,400);
    assert.equal((await review(order,{decision:'reject',note:'官方账单未查到，请核对'})).status,200);
    assert.equal(getOrder(order.id).status,'pending');assert.equal(stock(id),4);
    await request('/admin/personal-payments/alipay_personal','PUT',{...personalSettings,enabled:false,recipient:'新收款人'},admin);
    const resumed=await request('/payment/pay','POST',{order_id:order.id,payment_method:'alipay_personal'});
    assert.equal(resumed.status,200);assert.equal(resumed.body.data.recipient,'测试收款人');
    assert.equal((await request('/admin/orders/'+order.id+'/status','PUT',{status:'cancelled'},admin)).status,409);
    assert.equal((await review(order,{decision:'cancel',note:'核对未收到款，取消订单'})).status,200);
    assert.equal(getOrder(order.id).status,'cancelled');assert.equal(stock(id),5);
    assert.equal((await review(order,{decision:'cancel',note:'retry'})).status,409);assert.equal(stock(id),5);
    assert.equal((await review(order)).status,409);
    assert.equal((await request('/payment/personal/'+order.id+'/claim','POST',{reference:'late'})).status,409);
  });
});

test('WeChat raw-body RSA verification and authenticated decryption reject tampering',()=>{
  const {createWechat}=require('../services/wechat-live');
  const config={appid:'wx123',mchid:'1900001',privateKey:keypair.privateKey,platformPublicKey:keypair.publicKey,platformSerial:'PUB_KEY_ID_TEST',merchantSerialNumber:'TEST_CERT',apiV3Key:'a'.repeat(32),notifyUrl:'https://shop.test/api/payment/wechat/notify'};
  const client=createWechat(config);
  const payload={appid:config.appid,mchid:config.mchid,out_trade_no:'test-wechat-order',transaction_id:'wx-test-trade',trade_state:'SUCCESS',amount:{total:8050,currency:'CNY'}};
  const cipher=crypto.createCipheriv('aes-256-gcm',Buffer.from(config.apiV3Key),Buffer.from('123456789012'));
  cipher.setAAD(Buffer.from('transaction'));
  const encrypted=Buffer.concat([cipher.update(JSON.stringify(payload)),cipher.final(),cipher.getAuthTag()]).toString('base64');
  const raw=JSON.stringify({event_type:'TRANSACTION.SUCCESS',resource:{algorithm:'AEAD_AES_256_GCM',nonce:'123456789012',associated_data:'transaction',ciphertext:encrypted}},null,2);
  const timestamp=String(Math.floor(Date.now()/1000)), nonce='nonce';
  const headers={'wechatpay-timestamp':timestamp,'wechatpay-nonce':nonce,'wechatpay-serial':config.platformSerial,'wechatpay-signature':crypto.sign('RSA-SHA256',Buffer.from(`${timestamp}\n${nonce}\n${raw}\n`),keypair.privateKey).toString('base64')};
  assert.equal(client.verifyNotify(headers,raw).amountCents,8050);
  assert.throws(()=>client.verifyNotify(headers,JSON.stringify(JSON.parse(raw))));
  assert.throws(()=>client.verifyNotify({...headers,'wechatpay-serial':'wrong'},raw));
  assert.throws(()=>client.verifyNotify({...headers,'wechatpay-timestamp':'1'},raw));
});

for(const page of ['public/index.html','../frontend/index.html']) test(page+': cart/order fields and money/date rendering no longer produce NaN',()=>{
  const html=fs.readFileSync(path.join(__dirname,'..',page),'utf8');
  const script=html.slice(html.indexOf('  function normalizeLine('),html.indexOf('  // ========== 全局 Store'));
  const context={URL,API_BASE_URL:'/api',window:{location:{href:'https://shop.test/'}},order:{id:4,order_no:'ZYH123',total_amount:149,created_at:'2026-08-27 12:30:00',items:[{product_name:'毛笔',quantity:2,price:68.5,image:'/image.png'}]}};
  const result=vm.runInNewContext(script+'\n({order:normalizeOrder(order),invalidDate:formatDate(undefined),price:formatShortPrice(68.5),date:formatDate(order.created_at)})',context);
  assert.equal(result.order.items[0].qty,2);assert.equal(result.order.items[0].name,'毛笔');assert.equal(result.order.payAmount,149);assert.equal(result.order.orderNo,'ZYH123');
  assert.equal(result.invalidDate,'—');assert.equal(result.price,'¥ 68.50');assert.equal(result.date,'2026-08-27 12:30');
});
